spring.application.name=prelim-exam

spring.datasource.url=jdbc:mysql://localhost:3310/prelim_db
spring.datasource.username=root
spring.datasource.password=0lb8563423_
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
